language: go
go:
  - 1.7.x
  - 1.8.x
  - master

install:
  - go get -v github.com/revel/cmd/revel
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.12.3 && go install && cd -
  - glide install

script: revel test github.com/guillaumemaka/realworld-starter-kit-go-revel test